### PR TITLE
Adding stringsdict support

### PR DESCRIPTION
**Pull request by levinli303**
For strings that contains `%#@xxx@` create .stringsdict entry instead of .strings entry. By default it is turned off.

`generate_files` is `generate_dot_strings_files` but with an option to generate `.stringsdict` when matches are found
`has_changes` also has a new parameter to control whether or not to detect .stringsdict changes. default to not detect so as to not break existing code.

### CODE REVIEW

**Comment by levinli303** [comment]
Closes #4

**Comment by levinli303** [comment]
@dalemyers can you take a look?

**Review by ghost — APPROVED** [review]
I'm pretty swamped right now, so I haven't been able to review this thoroughly. A quick skim looks good though.

**Comment by ghost** [comment]
(And one day I'll remember to use the right Github account first time)

**Review by dalemyers — APPROVED** [review]

**Pull request merged**
